### KNN Implementation

In [22]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [23]:
heart_data = pd.read_csv("heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [24]:
X = heart_data.drop("target", axis=1)
y = heart_data['target']

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [25]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
print(y_train[y_train==1].count())
print(y_train[y_train==0].count())

# split is good

133
109

In [28]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
X_train

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [30]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

precision = precision_score(y_test , y_pred)
print(precision)

recall = recall_score(y_test , y_pred)
print(recall)

0.8524590163934426
0.9259259259259259
0.78125

In [31]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

precision = precision_score(y_test , y_pred)
print(precision)

recall = recall_score(y_test , y_pred)
print(recall)

0.9016393442622951
0.9333333333333333
0.875

In [32]:
model = KNeighborsClassifier(n_neighbors=7) ## Best score till now
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

precision = precision_score(y_test , y_pred)
print(precision)

recall = recall_score(y_test , y_pred)
print(recall)

0.9180327868852459
0.9354838709677419
0.90625

In [33]:
model = KNeighborsClassifier(n_neighbors=9)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

precision = precision_score(y_test , y_pred)
print(precision)

recall = recall_score(y_test , y_pred)
print(recall) # decreased

0.9016393442622951
0.9333333333333333
0.875

#### we use cross validation for optimal k value

### Cross validation for hyperparameter tuning using GridSearchCv

In [34]:
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()

param_grid = {'n_neighbors': [3, 5, 7, 9]}

grid_search = GridSearchCV(knn, param_grid, cv=5)
grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

model = grid_search.best_estimator_
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

precision = precision_score(y_test , y_pred)
print(f"Precision: {precision}")

recall = recall_score(y_test , y_pred)
print(f"Recall: {recall}")

# the results may be different from normal KNN because of the cross-validation and hyperparameter tuning. The best parameters found by GridSearchCV may lead to better performance on the test set compared to manually selecting the number of neighbors.

Best parameters: {'n_neighbors': 5}
Best cross-validation score: 0.8141156462585034
Accuracy: 0.9016393442622951
Precision: 0.9333333333333333
Recall: 0.875

In [35]:
res = pd.DataFrame(grid_search.cv_results_)
print(res)

   mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.004005      0.002287         0.011213        0.005853
1       0.003425      0.001642         0.007387        0.002644
2       0.002911      0.001288         0.011216        0.003569
3       0.003363      0.001531         0.008878        0.005540

   param_n_neighbors              params  split0_test_score  \
0                  3  {'n_neighbors': 3}           0.816327
1                  5  {'n_neighbors': 5}           0.775510
2                  7  {'n_neighbors': 7}           0.755102
3                  9  {'n_neighbors': 9}           0.734694

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.795918           0.854167           0.750000           0.812500
1           0.836735           0.833333           0.770833           0.854167
2           0.857143           0.812500           0.750000           0.833333
3           0.836735           0.833333           0.770833           0.833333

   mean_test_score  std_test_score  rank_test_score
0         0.805782        0.033783                2
1         0.814116        0.034202                1
2         0.801616        0.042510                4
3         0.801786        0.041644                3

In [36]:
print(res[['param_n_neighbors', 'mean_test_score']])

   param_n_neighbors  mean_test_score
0                  3         0.805782
1                  5         0.814116
2                  7         0.801616
3                  9         0.801786

### Using Pipeline

In [37]:
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])



param_grid = {'knn__n_neighbors': [3, 5, 7, 9]}

grid_search = GridSearchCV(
    pipeline, 
    param_grid, 
    cv=5,
    scoring='recall'
)
grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

model = grid_search.best_estimator_
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

precision = precision_score(y_test , y_pred)
print(f"Precision: {precision}")

recall = recall_score(y_test , y_pred)
print(f"Recall: {recall}")

Best parameters: {'knn__n_neighbors': 7}
Best cross-validation score: 0.8717948717948717
Accuracy: 0.9180327868852459
Precision: 0.9354838709677419
Recall: 0.90625