### Employee Turnover

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score

In [2]:
emp_data = pd.read_csv("employee_turnover.csv")
emp_data.head()

   Job_Satisfaction  ...  Employee_Turnover
0          0.562326  ...                  0
1          0.017041  ...                  0
2          0.774699  ...                  1
3          0.628174  ...                  0
4          0.799183  ...                  0

[5 rows x 16 columns]

In [3]:
emp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB

In [4]:
emp_data.describe()

       Job_Satisfaction  ...  Employee_Turnover
count       1350.000000  ...        1350.000000
mean           0.506386  ...           0.497778
std            0.291505  ...           0.500180
min            0.001738  ...           0.000000
25%            0.263051  ...           0.000000
50%            0.525340  ...           0.000000
75%            0.750987  ...           1.000000
max            0.998692  ...           1.000000

[8 rows x 16 columns]

In [17]:
X = emp_data.drop('Employee_Turnover', axis=1)
y = emp_data['Employee_Turnover']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
print(y_train[y_train == 1].count())
print(y_train[y_train == 0].count())

558
522

In [20]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")

Accuracy: 0.8851851851851852
Precision: 0.832

In [25]:
# L2 Regularization using Ridge Classifier
from sklearn.linear_model import RidgeClassifier
ridge_model = RidgeClassifier()

ridge_model.fit(X_train, y_train)
ridge_y_pred = ridge_model.predict(X_test)

ridge_accuracy = accuracy_score(y_test, ridge_y_pred)
ridge_precision = precision_score(y_test, ridge_y_pred)

print(f"Ridge Accuracy: {ridge_accuracy}")
print(f"Ridge Precision: {ridge_precision}")

Ridge Accuracy: 0.8851851851851852
Ridge Precision: 0.832

In [ ]:
# L1 Regulerization - there is no Lasso Classifier in sklearn, but we can use Logistic Regression with L1 penalty

l1_model = LogisticRegression(
    penalty='l1',
    solver='liblinear',   # or solver='saga'
    random_state=42
)

l1_model.fit(X_train, y_train)

l1_y_pred = l1_model.predict(X_test)

l1_accuracy = accuracy_score(y_test, l1_y_pred)
l1_precision = precision_score(y_test, l1_y_pred)

print(f"L1 Logistic Accuracy: {l1_accuracy}")
print(f"L1 Logistic Precision: {l1_precision}")

# The accuracy and precision are increased slightly

L1 Logistic Accuracy: 0.8888888888888888
L1 Logistic Precision: 0.8333333333333334